display_name: FlClash for Dler Cloud

icon: ./assets/images/icon.png

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash for Dler Cloud

categories:
  - Network

startup_notify: true

include: []