display_name: FlClash for Dler Cloud
package_name: flclash
maintainer:
  name: Dler Inc.
  email: support@dler.io

priority: optional
section: net
installed_size: 0
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-1
  - libkeybinder-3.0-0

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash for Dler Cloud

categories:
  - Network

startup_notify: true