script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
app_name: FlClash for Dler Cloud
publisher: Dler Inc.
display_name: FlClash for Dler Cloud
executable_name: FlClash.exe
output_base_file_name: FlClash.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin